config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "toppages#index"
  resources :plans do
    resources :comments, only: :create
  end
  resources :users, only: :show 
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :plan
  belongs_to :user
  validates :com, presence: true 
end

app/models/part.rb
class Part < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください' },
    { id: 2, name: '筋トレ' },
    { id: 3, name: 'ランニング' },
    { id: 4, name: 'ストレッチ' },
    { id: 5, name: 'Fitness情報' },
    { id: 6, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :plans
  
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :part
  belongs_to :user
  has_many   :comments, dependent: :destroy
  
  with_options presence: true do
  validates :part_id, numericality: { other_than: 1 } 
  validates :date 
  validates :text
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plans, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  with_options presence: true do
    validates :nickname
  end
  validates :password, length: { minimum: 6},format:{with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configre_permitted_parameters, if: :devise_controller?

  def configre_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def after_sign_in_path_for(resource) 
    plans_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/plans/#{comment.plan.id}" 
  end

  private
  def comment_params
    params.require(:comment).permit(:com).merge(user_id: current_user.id, plan_id: params[:plan_id])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :move_to_index, except: [:index]
  before_action :set_plan, only: [ :edit, :show]
  def index
    get_week
    @plans = Plan.order("created_at DESC")
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to action: :index
      flash[:notice] = "投稿しました"
    else
      flash[:danger] = "空欄があります。投稿できません。"
      render :new
    end
  end

  def destroy
    plan = Plan.find(params[:id])
    plan.destroy
    redirect_to action: :index
    flash[:notice] = "削除しました"
  end

  def edit
    if current_user.id == @plan.user_id || @plan.text.blank? 
      render template: "plans/edit"
    else
      redirect_to root_path
    end
  end

  def update
    plan = Plan.find(params[:id])
    plan.update(plan_params)
    redirect_to action: :index
    flash[:notice] = "編集しました"
  end

  def show
    @comment = Comment.new
    @comments = @plan.comments.includes(:user)
  end

  

  private
  def plan_params
    params.require(:plan).permit(:text, :date, :part_id).merge(user_id: current_user.id)
  end
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def get_week
    require "date"
    @todays_date = Date.today
    @week_days = []
    plans = Plan.where(date: @todays_date..@todays_date + 6)
    7.times do |x|
      today_plans = []
      plans.each do |plan|
        today_plans.push(plan.date) if plan.date == @todays_date + x
      end
    end
  end



end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @plans = current_user.plans.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<%= render "shared/header" %>
  <div class="post-page">
  <div class="pos">
    <h3 class = "post-menu">fitness_menu</h3>
    <P class = "habits">投稿内容を編集できます</p>
  </div>
  <div class ="post-form">
    <%= form_with(model: @plan, local: true) do |f| %>
  <p class="post-text">Days</p>
    <%= f.date_field :date, class: 'date-select' %>
   <p class="post-text">Select</p>
    <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"genre-select"}) %>
   <p class="post-text">Posts</p>
    <%= f.text_area :text, placeholder: "例 腹筋30回ets...", rows: "6",class:"post-texts" %>


    <%= f.submit 'edit', class: "post-button" %>
   </div>
</div>
  
<% end %>


<%= render "shared/footer" %>

app/views/plans/index.html.erb
<%= render "shared/header" %>
<div class = "main-page">
 <div class = "main-title">
    <h2 class = "name" >Welcame <%= current_user.nickname %></h2>
    <%= link_to "Post", new_plan_path, class: "post" %>
 </div>
   <h3 class ="main-phrase">毎日のトレーニングの内容、トレーニング情報をPost(投稿)！<br>みんなとShareしよう！</h3>
<% if flash[:notice]%>
<h3 class = "flash-message"><%= flash[:notice]%></h3>
<% end %>
<div class = "main-contents">
  <h2 class = "main-posts">Posts!</h2>
   <ul class = "post-list">
      <% @plans.each do |plan| %>
      <li class = "list">
    <div class = "post-info">
      <h3 class ="user-name">
       <%= plan.user.nickname%>
      </h3>
      <div class = "post-data">  
        <span> <%= plan.date %><br><%= plan.part.name %></span>
      </div>
        <div class ="post-texts">
          <%= plan.text %>
        </div>
          <%= link_to "#{plan.user.nickname}さんの投稿にコメントしよう！",  plan_path(plan.id), method: :get ,class:"com-button"%> 
     </div>
     </li>    
  <% end %>
   </ul>
</div>  
</div>
<%= render "shared/footer" %>

app/views/plans/new.html.erb
<%= render "shared/header" %>
<div class="post-page">
  <div class="pos">
    <h3 class = "post-menu">fitness_menu</h3>
    <P class = "habits">本日のトレーニングの内容、トレーニングの情報をPostしよう！</p>
  </div>
  <% if flash[:danger]%>
  <h3 class = "flash-message"><%= flash[:danger]%></h3>
  <% end %>
  <div class ="post-form">
    <%= form_with(model: @plan, local: true) do |f| %>
  <p class="post-text">Days</p>
    <%= f.date_field :date, class: 'date-select' %>
   <p class="post-text">Select</p>
    <%= f.collection_select(:part_id, Part.all, :id, :name, {}, {class:"genre-select"}) %>
   <p class="post-text">Posts</p>
    <%= f.text_area :text, placeholder: "例 腹筋30回ets...", rows: "6",class:"post-texts" %>
    <%= f.submit 'Posts!', class: "post-button" %>
   </div>
</div>
  
<% end %>

<%= render "shared/footer" %>

app/views/plans/show.html.erb
<%= render "shared/header" %>
<div class="main-comments">
  <h1 class = "com-title" ><%= @plan.user.nickname %> post</h1>
 

    <ul class = "com-main"> 
      <li class="com-list">
        <div class = "comments-data">  
          <span><%= @plan.date%><br><%= @plan.part.name%></span>
        </div>
         <div class ="comments-text">
          <%= @plan.text%>
           </div>
            <p class ="sub-com-title">☟☟コメントしよう☟☟</p>
        <%= form_with(model: [@plan, @comment], local: true) do |form| %>
         <%= form.text_area :com, placeholder: "コメントする", rows: "2",class: 'com' %>
         <%= form.submit "Comment",class: "coms-button" %>     
        <% end %>
        </li> 
    </ul> 
    
     <div class="comments">
        <h3 class ="com-plan"> ☟☟☟コメント一覧☟☟☟</h3>
        <% @comments.reverse.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}", class:"com-table"%></strong>
          :<%= comment.com %>
        </p>
      <% end %>
      
     </div>
</div>


<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class ="footer">
  <div class ="container">
    <div class = "footer-left">
       <p>このサイトをシェアする</p>
       <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Let'go fitness" data-show-count="false">Tweet</a>
       <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    <div class = "footer-right">
      &copy; 2021 Let'go Fitness
    </div>
    <div class = "clear"></div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class = "header">
 <div class = "container">
   <div class = "header-left">
     <a href = "/" >Let'go Fitness</a>
   </div>
    
   <div class = "header-right">
     <% if user_signed_in? %>
      <%= link_to 'Logout',destroy_user_session_path , method: :delete, class: "header-button" %> 
      <%= link_to 'main page',plans_path ,class: "header-button"%>
      <%= link_to "My page",  "/users/#{current_user.id}",class: "header-button"%>
     <% else %>
      <%= link_to 'sign up', new_user_registration_path, class: "header-button" %>
      <%= link_to 'Login', new_user_session_path, class: "header-button" %>
     <% end %>
   </div>
  <div class = "clear"></div>
 </div>
</div>

app/views/toppages/index.html.erb
<%= render "shared/header" %>
<div class= "main">
<%# /タイトル部分 %>
   <section class="home-hero wrapper">
   <h2>運動を習慣化しよう！</h2>
   <p>
   運動を習慣化して健康的な体を手に入れませんか？
    <br><strong>【なりたい自分】</strong>にきっと慣れる！！
   </p>
   <% if user_signed_in? %>
     <%= link_to 'mainpage', new_user_registration_path, class: "sing-button" %>
   <% else %>
     <%= link_to 'sign up', new_user_registration_path, class: "sing-button" %>
   <% end %>
   </section>
<%# /グラフ部分 %>
 <div class="wrappaer content">  
   <div class="home-chart"> 
      <h2 class = "chart-title">運動習慣がない人</h2>
      <div class="pie"></div>
      <ul class ="list-style">
        <li class ="list-orenge">運動習慣が<strong>ない</strong>人約72%</li>
        <li class ="list-green">運動習慣が<strong>ある</strong>人約28%</li>
        <li class ="list-icon">※2018年厚生労働省調べ</li>
      </ul>
   </div>
   <div class="home-text">
      <h2 class ="text-title"><u>運動習慣がある人は４人に1人</u></h2>
      <p>
      厚生労働省の平成30年(2018)「国民健康・栄養調査」による「運動習慣者の状況」は左のグラフとなっている。
       <br>運動習慣のある者の割合は、男性で31.8％、女性で25.5％であり、この10 年間でみると、
       男性では有意な増減はなく、女性では有意に減少している。
       <br>本サイトでは、そんな現状を打破するために、日々の運動の投稿や運動の知識を共有し、<strong>運動習慣を得る</strong>ことが目的である。
      </p>
   </div> 
 </div>

 <%# /サブタイトル部分 %>
  <section class = "home-sub">
   <h2><u>バランスの良い食事を！</u></h2>
   <p>
   運動だけでは理想の体を手に入れることはできません。
   <br>Protein(タンパク質)、Fat（脂質）、Carbohydratre(炭水化物)をバランスよくとりましょう。
   <br>理想バランスはp15%、F25%、C60%と言われています。</p>
   </section>

<%# /サブタイトル部分2 %>

<div class="wrappaer content">  
   <div class="sub-chart"> 
      <h2 class = "sub-chart-title">20際以上の肥満の割合</h2>
      <div class="circle"></div>
      <ul class ="list-chart">
        <li class ="list-blue">BMIが25以下</li>
        <li class ="list-yellow">BMIが25以上</li>
        <li class ="icon">※2019年厚生労働省調べ</li>
      </ul>
   </div>
   <div class="home-text">
      <h2 class ="sub-text-title"><u>男性は約３割、女性は約２割が肥満</u></h2>
      <p>
      厚生労働省「国民健康・栄養調査報告」によると、20歳以上の人の肥満の割合は男性33.0％、女性22.3％となっています。
      </p>
   </div> 
 </div>

 <%# /サービスイメージ %>
 <section class="service wrapper">
   <h2><u>サービスイメージ</u></h2>
   <p>
    毎日のトレーニングの記録、トレーニングの疑問点を投稿できます。
    <br>気になった投稿にコメントすることもできます。
    毎日の投稿を記録し他の人と共有することによって、運動を習慣化することが目的です！
    <br><strong>毎日の積み重ねがなりたい自分になる第一歩です！</strong>

   </p>
   </section>
 
</div>   
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="my-pages">
   <h1 class ="my-page-title"><%= @nickname %> Posts</h1>
   <ul class = "post-list">
    <% @plans.each do |plan| %>
     <li class = "list">
  <div class ="post-info">
      <%= plan.date %>
  <div class = "post-date">  
   <%= plan.part.name%>
   </div>
   <div class ="post-texts">
  <%= plan.text%>
  </div>
  <%= link_to '編集', edit_plan_path(plan.id), method: :get, class:"my-page-button"%>
   <%= link_to '削除', plan_path(plan.id), method: :delete,class:"my-page-button" %>
  </li>
 <% end %>
 </ul>
</div>




<%= render "shared/footer" %>